project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "*.md"
  post-render:
    - _post_render.py

website:
  title: "Tiago Paixão"
  site-url: https://tiagopaixao.com
  favicon: assets/favicon.png
  search: true
  navbar:
    background: light
    foreground: dark
    pinned: true
    right:
      - projects.qmd
      - blog.qmd
      - publications.qmd
      - cv.qmd
      - href: about.qmd
        text: About
format:
  html:
    theme: journal
    css: styles.css
    toc: false


